== Spring Pulsar Basic Demo

=== Components.
1. Basic producer using `PulsarTemplate`
2. Basic consumer using `PulsarListener`

=== Building and Running the application
Check out this repository.

==== Building
----
./mvnw clean package
----

==== Running
Make sure that you have Pulsar running locally (`localhost:6650`).

Then simply run the main application from your IDE or from the command line with the following command:
----
./mvnw spring-boot:run`
----
TIP: The above command also results in `add-opens` being set on the JVM

===== Timing Info
You can see the overall duration and send rate for the producer by setting the `timing.enabled` property to `true` in the `application.yml` prior to running the samples.

=== Vanilla Pulsar Demo
There is also a demo application with feature parity that uses regular Pulsar rather than Spring Pulsar. This is helpful to show the simplification that Spring Pulsar brings as well as compare / contrast the application run's timings and behavior.

To execute the Vanilla Pulsar demo simply run the application from your IDE or from the command line with the following command:

----
./mvnw spring-boot:run -Dstart.class="com.example.demo.vanillapulsar.VanillaPulsarDemoApplication"
----
TIP: The above command also results in `add-opens` being set on the JVM
